# Generated by Django 6.0.2 on 2026-02-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='show_id',
            new_name='show',
        ),
    ]
